### ISSUE TITLE
Clarification of number type

### ISSUE THREAD

**Issue by garethsb** [AMWA-TV/nmos-event-tally#67]
Number _state_ payloads in IS-07 have a `value` which may be integer or floating point, and a `scale` which is a positive integer (or 1 if omitted).

The number _type_ defines 'min', 'max' and 'step'.

Are the specified 'min' and 'max' values inclusive or exclusive? I'm assuming both inclusive?

The 'step' value is optional. The schema doesn't define a default but the documentation at [Event types - number](https://github.com/AMWA-TV/nmos-event-tally/blob/v1.0.x/docs/3.0.%20Event%20types.md#23-number) says the default is 1.

That seems awkward with floating point values?

I.e. is the following example valid, or would I need to add e.g. `"step": { "value": 0.5 }`?

**/type**

```json
{
  "type": "number",
  "min": { "value": 4.2 },
  "max": { "value": 5.7 }
}
```

**/state**

```json
{
    "event_type": "number",
    "payload": { "value": 4.7 }
}

**Comment by mjeras** [comment]
`min` and `max` are supposed to be inclusive. If `step` is omitted, it means that any value in that range is allowed, so that sample is valid. If step is present, then only `4.2`, `4.7`, `5.2` and `5.7` would be allowed, but it would still be a valid sample, only this time with a limited number of values. Of course, it is a bit ambiguous what happens if `max-min` is not a multiple of `step` - that could be either an invalid sample, or we could say all the values in the for of `min+N*step` (N is a integer >= 0) that are `<= max` are allowed.

**Comment by garethsb** [comment]
That's clear. I'll submit a PR to make clear min/max are inclusive and fix the description of step in https://github.com/AMWA-TV/nmos-event-tally/blob/v1.0.x/docs/3.0.%20Event%20types.md#23-number.
